### ISSUE TITLE
v1.6.2

### ISSUE THREAD

**Issue by jccarte** [cloudfoundry/python-buildpack-release#2]
I am not sure what the release timelines are for the bosh release vs the buildpack release, but is it possible to get the bosh release updated to v1.6.2.

**Comment by sclevine** [comment]
Hi @jccarte,

These online buildpack BOSH release repos are gated by integration with cf-deployment:
https://buildpacks.ci.cf-app.com/teams/main/pipelines/cf-release

We're having some trouble with our edge deployments right now, so that process is delayed. This repo will be updated automatically when those deployments are fixed.
